require "user.options"
require "user.keymaps"
require "user.plugins"
require "user.colorscheme"
require "user.gitsigns"
require "user.impatient"
require "user.whichkey"
require "user.alpha"
require "user.lualine"
require "user.lspconfig"
require "user.cmp"
require "user.treesitter"
require "user.autotag"
require "user.autopairs"
require "user.telescope"
require "user.bufferline"
require "user.lspsaga"
require "user.nvimtree"
require "user.toggleterm"
-- TODO: Add prettier and null-ls

-- Might want: dinhuy258/git.nvim, williamboman/mason.nvim
